In [75]:
import pandas as pd
import numpy as np
import duckdb
import json

In [76]:
conn = duckdb.connect('../data/bicimad.db',read_only=True)
conn

In [77]:
type(conn)

duckdb.DuckDBPyConnection

In [78]:
my_sql = conn.sql('SELECT* FROM bicimad_stations')
my_sql

┌───────┬──────────────────────┬───────┬───┬────────────┬────────────────────┬───────────────┬──────────────────────┐
│  id   │         name         │ light │ … │ free_bases │ reservations_count │ geometry.type │ geometry.coordinates │
│ int64 │       varchar        │ int64 │   │   int64    │       int64        │    varchar    │       varchar        │
├───────┼──────────────────────┼───────┼───┼────────────┼────────────────────┼───────────────┼──────────────────────┤
│     1 │ 1a - Puerta del So…  │     3 │ … │          0 │                  0 │ Point         │ [-3.7018341, 40.41…  │
│     2 │ 1b - Puerta del So…  │     3 │ … │          0 │                  0 │ Point         │ [-3.70160293806045…  │
│     3 │ 2 - Miguel Moya      │     3 │ … │          0 │                  0 │ Point         │ [-3.7058415, 40.42…  │
│     4 │ 3 - Plaza Conde Su…  │     2 │ … │          9 │                  0 │ Point         │ [-3.7069171, 40.43…  │
│     5 │ 4 - Malasaña         │     1 │ … │          1 │                  0 │ Point         │ [-3.7025875, 40.42…  │
│     6 │ 5 - Fuencarral       │     1 │ … │          0 │                  0 │ Point         │ [-3.70205, 40.42852] │
│     7 │ 6 - Colegio Arquit…  │     3 │ … │          0 │                  0 │ Point         │ [-3.698447, 40.424…  │
│     8 │ 7 - Hortaleza        │     3 │ … │          0 │                  0 │ Point         │ [-3.6977715, 40.42…  │
│     9 │ 8 - Alonso Martínez  │     1 │ … │          0 │                  0 │ Point         │ [-3.6954403, 40.42…  │
│    10 │ 9 - Plaza de San M…  │     2 │ … │         10 │                  0 │ Point         │ [-3.7095084, 40.41…  │
│     · │        ·             │     · │ · │          · │                  · │   ·           │          ·           │
│     · │        ·             │     · │ · │          · │                  · │   ·           │          ·           │
│     · │        ·             │     · │ · │          · │                  · │   ·           │          ·           │
│   260 │ 252 - Chamartín      │     3 │ … │         13 │                  0 │ Point         │ [-3.68391, 40.4716]  │
│   261 │ 253 - Doctor Fleming │     2 │ … │         11 │                  0 │ Point         │ [-3.68844, 40.45546] │
│   262 │ 254 - Pío XII        │     1 │ … │          6 │                  0 │ Point         │ [-3.67712, 40.46041] │
│   263 │ 255 - López Pozas    │     0 │ … │         19 │                  0 │ Point         │ [-3.68514, 40.46361] │
│   264 │ 256 - Reina Victoria │     2 │ … │         14 │                  0 │ Point         │ [-3.71383, 40.44635] │
│   265 │ 257 - INEF           │     0 │ … │         19 │                  0 │ Point         │ [-3.72997, 40.43896] │
│   266 │ 258 - Ciudad Unive…  │     2 │ … │         14 │                  0 │ Point         │ [-3.72699, 40.44375] │
│   267 │ 259 - Ciudad Unive…  │     2 │ … │         10 │                  0 │ Point         │ [-3.72693, 40.44342] │
│   268 │ 260 - Facultad Bio…  │     2 │ … │         10 │                  0 │ Point         │ [-3.7272945, 40.44…  │
│   269 │ 261 - Facultad Der…  │     2 │ … │         16 │                  0 │ Point         │ [-3.72937, 40.45109] │
├───────┴──────────────────────┴───────┴───┴────────────┴────────────────────┴───────────────┴──────────────────────┤
│ 264 rows (20 shown)                                                                          13 columns (7 shown) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [79]:
df = my_sql.df()
df

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry.type,geometry.coordinates
0,1,1a - Puerta del Sol A,3,1a,Puerta del Sol nº 1,1,1,30,0,0,0,Point,"[-3.7018341, 40.4172137]"
1,2,1b - Puerta del Sol B,3,1b,Puerta del Sol nº 1,1,1,30,0,0,0,Point,"[-3.701602938060457, 40.41731271011562]"
2,3,2 - Miguel Moya,3,2,Calle Miguel Moya nº 1,1,1,24,0,0,0,Point,"[-3.7058415, 40.4205886]"
3,4,3 - Plaza Conde Suchil,2,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,9,9,0,Point,"[-3.7069171, 40.4302937]"
4,5,4 - Malasaña,1,4,Calle Manuela Malasaña nº 5,1,0,24,23,1,0,Point,"[-3.7025875, 40.4285524]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,265,257 - INEF,0,257,Avenida Juan de Herrera frente a la calle Paul...,1,0,24,3,19,0,Point,"[-3.72997, 40.43896]"
260,266,258 - Ciudad Universitaria 1,2,258,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,9,14,0,Point,"[-3.72699, 40.44375]"
261,267,259 - Ciudad Universitaria 2,2,259,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,12,10,0,Point,"[-3.72693, 40.44342]"
262,268,260 - Facultad Biología,2,260,Calle José Antonio Novais frente al nº 12,1,0,24,12,10,0,Point,"[-3.7272945, 40.4483322]"
263,269,261 - Facultad Derecho,2,261,Avenida Complutense nº 23,1,0,24,8,16,0,Point,"[-3.72937, 40.45109]"

In [80]:
df['geometry.coordinates']

0                     [-3.7018341, 40.4172137]
1      [-3.701602938060457, 40.41731271011562]
2                     [-3.7058415, 40.4205886]
3                     [-3.7069171, 40.4302937]
4                     [-3.7025875, 40.4285524]
                        ...
259                       [-3.72997, 40.43896]
260                       [-3.72699, 40.44375]
261                       [-3.72693, 40.44342]
262                   [-3.7272945, 40.4483322]
263                       [-3.72937, 40.45109]
Name: geometry.coordinates, Length: 264, dtype: object

In [81]:
bicimad = df[['name','address','geometry.coordinates']]
bicimad

,name,address,geometry.coordinates
0,1a - Puerta del Sol A,Puerta del Sol nº 1,"[-3.7018341, 40.4172137]"
1,1b - Puerta del Sol B,Puerta del Sol nº 1,"[-3.701602938060457, 40.41731271011562]"
2,2 - Miguel Moya,Calle Miguel Moya nº 1,"[-3.7058415, 40.4205886]"
3,3 - Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,"[-3.7069171, 40.4302937]"
4,4 - Malasaña,Calle Manuela Malasaña nº 5,"[-3.7025875, 40.4285524]"
...,...,...,...
259,257 - INEF,Avenida Juan de Herrera frente a la calle Paul...,"[-3.72997, 40.43896]"
260,258 - Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,"[-3.72699, 40.44375]"
261,259 - Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,"[-3.72693, 40.44342]"
262,260 - Facultad Biología,Calle José Antonio Novais frente al nº 12,"[-3.7272945, 40.4483322]"
263,261 - Facultad Derecho,Avenida Complutense nº 23,"[-3.72937, 40.45109]"

In [82]:
bicimad.columns = ['BiciMAD Station','Station Location','Coordinates']
bicimad
#type(bicimad)

,BiciMAD Station,Station Location,Coordinates
0,1a - Puerta del Sol A,Puerta del Sol nº 1,"[-3.7018341, 40.4172137]"
1,1b - Puerta del Sol B,Puerta del Sol nº 1,"[-3.701602938060457, 40.41731271011562]"
2,2 - Miguel Moya,Calle Miguel Moya nº 1,"[-3.7058415, 40.4205886]"
3,3 - Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,"[-3.7069171, 40.4302937]"
4,4 - Malasaña,Calle Manuela Malasaña nº 5,"[-3.7025875, 40.4285524]"
...,...,...,...
259,257 - INEF,Avenida Juan de Herrera frente a la calle Paul...,"[-3.72997, 40.43896]"
260,258 - Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,"[-3.72699, 40.44375]"
261,259 - Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,"[-3.72693, 40.44342]"
262,260 - Facultad Biología,Calle José Antonio Novais frente al nº 12,"[-3.7272945, 40.4483322]"
263,261 - Facultad Derecho,Avenida Complutense nº 23,"[-3.72937, 40.45109]"

In [83]:
bicimad['Coordinates'] = bicimad['Coordinates'].str.strip('[]')
bicimad

C:\Users\mujib\AppData\Local\Temp\ipykernel_26960\889294646.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bicimad['Coordinates'] = bicimad['Coordinates'].str.strip('[]')

,BiciMAD Station,Station Location,Coordinates
0,1a - Puerta del Sol A,Puerta del Sol nº 1,"-3.7018341, 40.4172137"
1,1b - Puerta del Sol B,Puerta del Sol nº 1,"-3.701602938060457, 40.41731271011562"
2,2 - Miguel Moya,Calle Miguel Moya nº 1,"-3.7058415, 40.4205886"
3,3 - Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,"-3.7069171, 40.4302937"
4,4 - Malasaña,Calle Manuela Malasaña nº 5,"-3.7025875, 40.4285524"
...,...,...,...
259,257 - INEF,Avenida Juan de Herrera frente a la calle Paul...,"-3.72997, 40.43896"
260,258 - Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,"-3.72699, 40.44375"
261,259 - Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,"-3.72693, 40.44342"
262,260 - Facultad Biología,Calle José Antonio Novais frente al nº 12,"-3.7272945, 40.4483322"
263,261 - Facultad Derecho,Avenida Complutense nº 23,"-3.72937, 40.45109"

In [84]:
bicimad[['Latitude', 'Longitude']] = bicimad['Coordinates'].apply(lambda x: pd.Series({'Latitude': x[0], 'Longitude': x[1]}))
bicimad

C:\Users\mujib\AppData\Local\Temp\ipykernel_26960\2877901158.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bicimad[['Latitude', 'Longitude']] = bicimad['Coordinates'].apply(lambda x: pd.Series({'Latitude': x[0], 'Longitude': x[1]}))
C:\Users\mujib\AppData\Local\Temp\ipykernel_26960\2877901158.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bicimad[['Latitude', 'Longitude']] = bicimad['Coordinates'].apply(lambda x: pd.Series({'Latitude': x[0], 'Longitude': x[1]}))

,BiciMAD Station,Station Location,Coordinates,Latitude,Longitude
0,1a - Puerta del Sol A,Puerta del Sol nº 1,"-3.7018341, 40.4172137",-,3
1,1b - Puerta del Sol B,Puerta del Sol nº 1,"-3.701602938060457, 40.41731271011562",-,3
2,2 - Miguel Moya,Calle Miguel Moya nº 1,"-3.7058415, 40.4205886",-,3
3,3 - Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,"-3.7069171, 40.4302937",-,3
4,4 - Malasaña,Calle Manuela Malasaña nº 5,"-3.7025875, 40.4285524",-,3
...,...,...,...,...,...
259,257 - INEF,Avenida Juan de Herrera frente a la calle Paul...,"-3.72997, 40.43896",-,3
260,258 - Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,"-3.72699, 40.44375",-,3
261,259 - Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,"-3.72693, 40.44342",-,3
262,260 - Facultad Biología,Calle José Antonio Novais frente al nº 12,"-3.7272945, 40.4483322",-,3
263,261 - Facultad Derecho,Avenida Complutense nº 23,"-3.72937, 40.45109",-,3

In [85]:
bicimad[['Longitude', 'Latitude']] = bicimad['Coordinates'].str.split(',', expand=True)
bicimad

C:\Users\mujib\AppData\Local\Temp\ipykernel_26960\1680687527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bicimad[['Longitude', 'Latitude']] = bicimad['Coordinates'].str.split(',', expand=True)

,BiciMAD Station,Station Location,Coordinates,Latitude,Longitude
0,1a - Puerta del Sol A,Puerta del Sol nº 1,"-3.7018341, 40.4172137",40.4172137,-3.7018341
1,1b - Puerta del Sol B,Puerta del Sol nº 1,"-3.701602938060457, 40.41731271011562",40.41731271011562,-3.701602938060457
2,2 - Miguel Moya,Calle Miguel Moya nº 1,"-3.7058415, 40.4205886",40.4205886,-3.7058415
3,3 - Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,"-3.7069171, 40.4302937",40.4302937,-3.7069171
4,4 - Malasaña,Calle Manuela Malasaña nº 5,"-3.7025875, 40.4285524",40.4285524,-3.7025875
...,...,...,...,...,...
259,257 - INEF,Avenida Juan de Herrera frente a la calle Paul...,"-3.72997, 40.43896",40.43896,-3.72997
260,258 - Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,"-3.72699, 40.44375",40.44375,-3.72699
261,259 - Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,"-3.72693, 40.44342",40.44342,-3.72693
262,260 - Facultad Biología,Calle José Antonio Novais frente al nº 12,"-3.7272945, 40.4483322",40.4483322,-3.7272945
263,261 - Facultad Derecho,Avenida Complutense nº 23,"-3.72937, 40.45109",40.45109,-3.72937

In [90]:
bicimad.drop(['Coordinates'], axis=1)

,BiciMAD Station,Station Location,Latitude,Longitude
0,1a - Puerta del Sol A,Puerta del Sol nº 1,40.4172137,-3.7018341
1,1b - Puerta del Sol B,Puerta del Sol nº 1,40.41731271011562,-3.701602938060457
2,2 - Miguel Moya,Calle Miguel Moya nº 1,40.4205886,-3.7058415
3,3 - Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,40.4302937,-3.7069171
4,4 - Malasaña,Calle Manuela Malasaña nº 5,40.4285524,-3.7025875
...,...,...,...,...
259,257 - INEF,Avenida Juan de Herrera frente a la calle Paul...,40.43896,-3.72997
260,258 - Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,40.44375,-3.72699
261,259 - Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,40.44342,-3.72693
262,260 - Facultad Biología,Calle José Antonio Novais frente al nº 12,40.4483322,-3.7272945
263,261 - Facultad Derecho,Avenida Complutense nº 23,40.45109,-3.72937

In [88]:
bicimad.to_csv('../data/bicimad.csv', index=False)